import { defaultPrivacy, type ActivityItem, type FamilyEvent, type FamilyTreeRecord, type Person, type Photo, type Relationship, type Source, type Story } from "./types";

const TREE_ID = "tree_williams";
const now = "2026-09-09T10:00:00.000Z";

const privacy = defaultPrivacy();

export const WILLIAMS_TREE: FamilyTreeRecord = {
  id: TREE_ID,
  name: "The Williams Family",
  ownerName: "Janelle",
  shareAccess: "family",
  hideLivingDates: true,
  hideContactInfo: true,
  hidePrivateNotes: true,
  hidePhotosPublic: false,
  inviteCode: "WILLIAMS",
  viewPasscode: "ROSE",
  editCode: "OAK-1935",
};

const photo = (id: string, extras: Partial<Person> & Pick<Person, "firstName" | "lastName" | "gender" | "birthDate">): Person => ({
  id,
  familyTreeId: TREE_ID,
  middleName: "",
  preferredName: "",
  deathDate: "",
  birthPlace: "",
  deathPlace: "",
  currentLocation: "",
  occupation: "",
  education: "",
  biography: "",
  email: "",
  phone: "",
  website: "",
  socialLinks: [],
  profilePhotoUrl: "",
  generation: 1,
  branch: "Williams",
  notes: "",
  privacy,
  createdAt: now,
  updatedAt: now,
  ...extras,
});

export const MOCK_PEOPLE: Person[] = [
  photo("robert", {
    firstName: "Robert",
    middleName: "James",
    lastName: "Williams",
    gender: "male",
    birthDate: "1935-03-14",
    deathDate: "2010-11-02",
    birthPlace: "Charleston, South Carolina",
    deathPlace: "Charleston, South Carolina",
    occupation: "Railroad engineer",
    education: "Charleston Technical Institute",
    biography:
      "Robert built a life around quiet reliability. He spent forty years with the Southern Railway, tended a pecan grove behind the house, and never missed Sunday supper. His letters home, written in a careful hand, are still kept in a cedar box in the hallway.",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 1,
    branch: "Williams",
  }),
  photo("margaret", {
    firstName: "Margaret",
    middleName: "Rose",
    lastName: "Williams",
    preferredName: "Margaret",
    gender: "female",
    birthDate: "1938-07-22",
    deathDate: "2015-04-18",
    birthPlace: "Savannah, Georgia",
    deathPlace: "Charleston, South Carolina",
    occupation: "Schoolteacher",
    education: "Wesleyan College",
    biography:
      "Margaret taught third grade for thirty-two years and kept a garden that neighbors still talk about. She pressed flowers into books, wrote the family recipes on index cards, and believed a well-set table could mend almost anything.",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 1,
    branch: "Williams",
  }),
  photo("james", {
    firstName: "James",
    middleName: "Robert",
    lastName: "Williams",
    gender: "male",
    birthDate: "1960-05-09",
    deathDate: "2020-08-30",
    birthPlace: "Charleston, South Carolina",
    deathPlace: "New York, New York",
    occupation: "Architect",
    education: "Columbia University",
    biography:
      "James brought the family's sense of craft north. He designed libraries and small museums, sketched on napkins, and called home every Sunday. He died too soon, but the light in the houses he drew still feels like him.",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 2,
    branch: "Williams",
  }),
  photo("patricia", {
    firstName: "Patricia",
    middleName: "Anne",
    lastName: "Williams",
    preferredName: "Patricia",
    gender: "female",
    birthDate: "1962-01-19",
    birthPlace: "Brooklyn, New York",
    currentLocation: "New York, New York",
    occupation: "Editor",
    education: "Barnard College",
    biography:
      "Patricia has a poet's ear and an editor's patience. She raised Daniel and Sarah among stacks of manuscripts and weekend trains to Charleston, and still keeps James's drafting table by the window.",
    email: "patricia@williams.family",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 2,
    branch: "Williams",
  }),
  photo("michael", {
    firstName: "Michael",
    middleName: "Thomas",
    lastName: "Williams",
    gender: "male",
    birthDate: "1965-09-03",
    birthPlace: "Charleston, South Carolina",
    currentLocation: "Asheville, North Carolina",
    occupation: "Cabinetmaker",
    education: "Rhode Island School of Design",
    biography:
      "Michael stayed closer to the lowcountry, then followed the mountains. He builds furniture by hand, writes the family stories no one else thinks to write down, and still uses his father's plane.",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 2,
    branch: "Williams",
  }),
  photo("linda", {
    firstName: "Linda",
    lastName: "Williams",
    preferredName: "Linda",
    gender: "female",
    birthDate: "1967-11-28",
    birthPlace: "San Francisco, California",
    currentLocation: "Asheville, North Carolina",
    occupation: "Landscape architect",
    education: "UC Berkeley",
    biography:
      "Linda designs gardens the way other people write letters — with patience, weather, and a long view. She married into the Williamses and brought West Coast light with her.",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 2,
    branch: "Williams",
  }),
  photo("elizabeth", {
    firstName: "Elizabeth",
    middleName: "Grace",
    lastName: "Carter",
    preferredName: "Elizabeth",
    gender: "female",
    birthDate: "1968-02-14",
    birthPlace: "Charleston, South Carolina",
    currentLocation: "Savannah, Georgia",
    occupation: "Pediatrician",
    education: "Emory University School of Medicine",
    biography:
      "Elizabeth is the family's steady compass. She kept Margaret's recipes, Robert's watch, and a practice full of children who still send her drawings.",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1559839734-34d77fa6d89d?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 2,
    branch: "Carter",
  }),
  photo("david", {
    firstName: "David",
    lastName: "Carter",
    gender: "male",
    birthDate: "1966-06-21",
    birthPlace: "Atlanta, Georgia",
    currentLocation: "Savannah, Georgia",
    occupation: "Historian",
    education: "University of Georgia",
    biography:
      "David maps family histories for a living and still gets quiet when the Williamses open the old albums. He married Elizabeth in her mother's garden.",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 2,
    branch: "Carter",
  }),
  photo("daniel", {
    firstName: "Daniel",
    middleName: "James",
    lastName: "Williams",
    gender: "male",
    birthDate: "1985-04-07",
    birthPlace: "New York, New York",
    currentLocation: "Brooklyn, New York",
    occupation: "Documentary photographer",
    education: "NYU Tisch",
    biography:
      "Daniel photographs the in-between moments — porches, train windows, the way light sits on a kitchen table. He is compiling a book of the family's faces across four generations.",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 3,
    branch: "Williams",
  }),
  photo("sarah", {
    firstName: "Sarah",
    middleName: "Margaret",
    lastName: "Williams",
    preferredName: "Sarah",
    gender: "female",
    birthDate: "1988-03-12",
    birthPlace: "New York, New York",
    currentLocation: "Brooklyn, New York",
    occupation: "Museum curator",
    education: "Yale University",
    biography:
      "Sarah curates American decorative arts and keeps the family archive with the same care. She is the one who started this tree — so Olivia and Noah would always know whose hands made the table they eat at.",
    email: "sarah@williams.family",
    phone: "(212) 555-0148",
    website: "https://sarahwilliams.studio",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 3,
    branch: "Williams",
  }),
  photo("alex", {
    firstName: "Alex",
    lastName: "Turner",
    gender: "male",
    birthDate: "1987-10-02",
    birthPlace: "Portland, Oregon",
    currentLocation: "Brooklyn, New York",
    occupation: "Composer",
    education: "Juilliard",
    biography:
      "Alex writes music for film and for the two small people who now dance in the hallway. He joined the family at Sarah's wedding under the oak in Charleston.",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 3,
    branch: "Turner",
  }),
  photo("emma", {
    firstName: "Emma",
    lastName: "Williams",
    gender: "female",
    birthDate: "1992-08-16",
    birthPlace: "Asheville, North Carolina",
    currentLocation: "Durham, North Carolina",
    occupation: "Botanist",
    education: "Duke University",
    biography:
      "Emma studies native plants and still sends her grandmother's pressed flowers to cousins in envelopes. She has Margaret's patience and Michael's hands.",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 3,
    branch: "Williams",
  }),
  photo("thomas", {
    firstName: "Thomas",
    lastName: "Williams",
    gender: "male",
    birthDate: "1995-12-01",
    birthPlace: "Asheville, North Carolina",
    currentLocation: "Charleston, South Carolina",
    occupation: "Restoration carpenter",
    education: "College of Charleston",
    biography:
      "Thomas came home to the houses his grandfather knew. He restores porches and floorboards, and is the one who found Robert's navy letters in the attic.",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 3,
    branch: "Williams",
  }),
  photo("olivia", {
    firstName: "Olivia",
    middleName: "Rose",
    lastName: "Williams",
    gender: "female",
    birthDate: "2015-06-20",
    birthPlace: "Brooklyn, New York",
    currentLocation: "Brooklyn, New York",
    education: "P.S. 29",
    biography: "Olivia loves drawing family portraits and asking who everyone was 'before they were old.' She has Sarah's eyes and Margaret's middle name.",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 4,
    branch: "Williams",
  }),
  photo("noah", {
    firstName: "Noah",
    middleName: "James",
    lastName: "Williams",
    gender: "male",
    birthDate: "2018-01-08",
    birthPlace: "Brooklyn, New York",
    currentLocation: "Brooklyn, New York",
    biography: "Noah is the youngest Williams — a collector of stones, songs, and questions. He calls the family tree 'the people picture.'",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=400&h=400&q=80",
    generation: 4,
    branch: "Williams",
  }),
];

function rel(
  id: string,
  personId: string,
  relatedPersonId: string,
  relationshipType: Relationship["relationshipType"],
): Relationship {
  return { id, familyTreeId: TREE_ID, personId, relatedPersonId, relationshipType, createdAt: now };
}

export const MOCK_RELATIONSHIPS: Relationship[] = [
  rel("r1", "robert", "margaret", "spouse"),
  rel("r2", "james", "patricia", "spouse"),
  rel("r3", "michael", "linda", "spouse"),
  rel("r4", "elizabeth", "david", "spouse"),
  rel("r5", "sarah", "alex", "partner"),

  rel("r6", "robert", "james", "parent"),
  rel("r7", "margaret", "james", "parent"),
  rel("r8", "robert", "michael", "parent"),
  rel("r9", "margaret", "michael", "parent"),
  rel("r10", "robert", "elizabeth", "parent"),
  rel("r11", "margaret", "elizabeth", "parent"),

  rel("r12", "james", "daniel", "parent"),
  rel("r13", "patricia", "daniel", "parent"),
  rel("r14", "james", "sarah", "parent"),
  rel("r15", "patricia", "sarah", "parent"),

  rel("r16", "michael", "emma", "parent"),
  rel("r17", "linda", "emma", "parent"),
  rel("r18", "michael", "thomas", "parent"),
  rel("r19", "linda", "thomas", "parent"),

  rel("r20", "sarah", "olivia", "parent"),
  rel("r21", "alex", "olivia", "parent"),
  rel("r22", "sarah", "noah", "parent"),
  rel("r23", "alex", "noah", "parent"),
];

export const MOCK_PHOTOS: Photo[] = [
  {
    id: "ph1",
    familyTreeId: TREE_ID,
    url: "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=1200&q=80",
    caption: "Family Christmas — 1998",
    date: "1998-12-24",
    location: "Charleston, South Carolina",
    description: "The last Christmas in Robert and Margaret's house before the kitchen was remodeled. James carved the turkey; the children sat on the stairs.",
    taggedPersonIds: ["sarah", "james", "patricia", "daniel", "robert", "margaret", "michael", "elizabeth"],
    isPrivate: false,
    uploadedAt: "2026-09-07T18:00:00.000Z",
  },
  {
    id: "ph2",
    familyTreeId: TREE_ID,
    url: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
    caption: "Sarah's Wedding",
    date: "2014-05-17",
    location: "Charleston, South Carolina",
    description: "Under the live oak in Margaret's garden, just as she had hoped.",
    taggedPersonIds: ["sarah", "alex", "patricia", "daniel", "michael", "linda", "elizabeth"],
    isPrivate: false,
    uploadedAt: "2026-09-06T12:00:00.000Z",
  },
  {
    id: "ph3",
    familyTreeId: TREE_ID,
    url: "https://images.unsplash.com/photo-1609220136736-443140cffd6f?auto=format&fit=crop&w=1200&q=80",
    caption: "Sunday on the stoop",
    date: "2022-06-12",
    location: "Brooklyn, New York",
    description: "Olivia insisted everyone wear yellow. Noah fell asleep on Alex's shoulder.",
    taggedPersonIds: ["sarah", "alex", "olivia", "noah"],
    isPrivate: false,
    uploadedAt: "2026-09-05T09:00:00.000Z",
  },
  {
    id: "ph4",
    familyTreeId: TREE_ID,
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    caption: "Sullivan's Island, 2004",
    date: "2004-07-04",
    location: "Sullivan's Island, South Carolina",
    description: "The whole family at the beach house. Robert still in his hat.",
    taggedPersonIds: ["robert", "margaret", "james", "michael", "elizabeth", "sarah", "daniel"],
    isPrivate: false,
    uploadedAt: "2026-09-01T09:00:00.000Z",
  },
  {
    id: "ph5",
    familyTreeId: TREE_ID,
    url: "https://images.unsplash.com/photo-1464476918261-8e4ddb6c4d0d?auto=format&fit=crop&w=1200&q=80",
    caption: "Robert, 1954",
    date: "1954-08-01",
    location: "Charleston, South Carolina",
    description: "A scanned photograph from the cedar box. Robert at nineteen, before the railway.",
    taggedPersonIds: ["robert"],
    isPrivate: false,
    uploadedAt: "2026-08-20T09:00:00.000Z",
  },
  {
    id: "ph6",
    familyTreeId: TREE_ID,
    url: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1200&q=80",
    caption: "Margaret in the garden",
    date: "1991-05-02",
    location: "Charleston, South Carolina",
    description: "Roses, a straw hat, and the same gold watch she wore every day.",
    taggedPersonIds: ["margaret"],
    isPrivate: false,
    uploadedAt: "2026-08-18T09:00:00.000Z",
  },
];

export const MOCK_STORIES: Story[] = [
  {
    id: "st1",
    familyTreeId: TREE_ID,
    title: "Grandma Rose's Journey to America",
    coverPhotoUrl:
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1400&q=80",
    date: "1924-04-11",
    location: "Savannah, Georgia",
    personIds: ["margaret"],
    isPrivate: false,
    createdAt: "2026-08-12T10:00:00.000Z",
    body: "Margaret's mother, Rose, crossed the Atlantic with a single trunk and a paper of seeds from her father's garden. She was seventeen. The ship docked in Savannah in a warm April rain, and she wrote that the air smelled like wet earth and oranges.\n\nThe seeds became the roses that Margaret later planted behind the Charleston house — the same garden where Elizabeth married David, and where Sarah stood with Alex ninety years later.\n\nWe tell this story because it is the first one. Everything else grows from it: the recipes, the names, the habit of keeping a little earth under the nails.",
  },
  {
    id: "st2",
    familyTreeId: TREE_ID,
    title: "Sarah's Wedding",
    coverPhotoUrl:
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1400&q=80",
    date: "2014-05-17",
    location: "Charleston, South Carolina",
    personIds: ["sarah", "alex", "patricia", "daniel", "michael"],
    isPrivate: false,
    createdAt: "2026-08-14T10:00:00.000Z",
    body: "They were married under the live oak in Margaret's garden. It had rained in the morning and then cleared, the way Charleston does, as if the weather had been asked politely.\n\nJames did not live to see it, but Patricia carried his handkerchief, and Daniel photographed the light on the leaves the way his father would have sketched it. Alex played a piece he had written for Sarah on a borrowed piano in the parlor, and Olivia — not yet born — was already a rumor in the toasts.",
  },
  {
    id: "st3",
    familyTreeId: TREE_ID,
    title: "The Williams Christmas, 1998",
    coverPhotoUrl:
      "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=1400&q=80",
    date: "1998-12-24",
    location: "Charleston, South Carolina",
    personIds: ["sarah", "james", "patricia", "daniel", "robert", "margaret"],
    isPrivate: false,
    createdAt: "2026-08-16T10:00:00.000Z",
    body: "Sarah was ten. She remembers the staircase, the smell of oranges and cloves, and Robert pretending not to know who had hung the pickles on the tree.\n\nEveryone was still here. That is the part that is hard to write and impossible not to. The photographs from that night are the ones the children reach for first.",
  },
  {
    id: "st4",
    familyTreeId: TREE_ID,
    title: "Robert and the Oak Tree",
    coverPhotoUrl:
      "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1400&q=80",
    date: "1972-06-01",
    location: "Charleston, South Carolina",
    personIds: ["robert", "margaret", "james", "michael", "elizabeth"],
    isPrivate: false,
    createdAt: "2026-08-02T10:00:00.000Z",
    body: "Robert planted a live oak the year Elizabeth was born. He said a family needed something that would outlast them on purpose. The children were not allowed to hang from it until they could name every cousin.\n\nThe tree is still there. Thomas trimmed it last spring and found Robert's pocketknife in the roots, rusted shut, initials still visible.",
  },
];

export const MOCK_EVENTS: FamilyEvent[] = [
  {
    id: "ev1",
    familyTreeId: TREE_ID,
    personId: "sarah",
    title: "Born",
    date: "1988-03-12",
    location: "New York, New York",
    description: "New York-Presbyterian Hospital",
  },
  {
    id: "ev2",
    familyTreeId: TREE_ID,
    personId: "sarah",
    title: "Graduated Yale",
    date: "2010-05-24",
    location: "New Haven, Connecticut",
    description: "History of Art",
  },
  {
    id: "ev3",
    familyTreeId: TREE_ID,
    personId: "sarah",
    title: "Married Alex Turner",
    date: "2014-05-17",
    location: "Charleston, South Carolina",
    description: "Margaret's garden",
  },
  {
    id: "ev4",
    familyTreeId: TREE_ID,
    personId: "sarah",
    title: "Olivia born",
    date: "2015-06-20",
    location: "Brooklyn, New York",
    description: "",
  },
  {
    id: "ev5",
    familyTreeId: TREE_ID,
    personId: "sarah",
    title: "Noah born",
    date: "2018-01-08",
    location: "Brooklyn, New York",
    description: "",
  },
];

export const MOCK_SOURCES: Source[] = [
  {
    id: "so1",
    familyTreeId: TREE_ID,
    title: "Birth certificate — Sarah Margaret Williams",
    type: "Vital record",
    citation: "New York City Department of Health, 1988, certificate 31884",
    url: "",
    relatedPersonIds: ["sarah"],
    notes: "Confirms birthplace and parents James Robert Williams and Patricia Anne Moore.",
  },
  {
    id: "so2",
    familyTreeId: TREE_ID,
    title: "1940 U.S. Census — Charleston County",
    type: "Census",
    citation: "U.S. Census Bureau, Charleston County, SC, 1940",
    url: "",
    relatedPersonIds: ["robert", "margaret"],
    notes: "Robert listed as son in the household on Tradd Street.",
  },
  {
    id: "so3",
    familyTreeId: TREE_ID,
    title: "Wedding invitation — Sarah & Alex",
    type: "Family document",
    citation: "Williams family papers, Charleston, 2014",
    url: "",
    relatedPersonIds: ["sarah", "alex"],
    notes: "Printed on cream stock with a pressed oak leaf.",
  },
  {
    id: "so4",
    familyTreeId: TREE_ID,
    title: "Southern Railway employment record",
    type: "Occupational",
    citation: "Southern Railway archives, 1955–1995",
    url: "",
    relatedPersonIds: ["robert"],
    notes: "Forty years of service. Pension correspondence included.",
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  { id: "a1", text: "Sarah Williams added a photo", detail: "Sunday on the stoop", time: "2 days ago" },
  { id: "a2", text: "Michael Williams added a story", detail: "Robert and the Oak Tree", time: "2 days ago" },
  { id: "a3", text: "Daniel Williams tagged four people", detail: "Family Christmas — 1998", time: "4 days ago" },
  { id: "a4", text: "Patricia Williams edited a profile", detail: "James Williams", time: "1 week ago" },
];

export const EMPTY_TREE: FamilyTreeRecord = {
  id: "tree_new",
  name: "Your Family",
  ownerName: "Janelle",
  shareAccess: "private",
  hideLivingDates: true,
  hideContactInfo: true,
  hidePrivateNotes: true,
  hidePhotosPublic: false,
  inviteCode: "FAMILY",
  viewPasscode: "PEACE",
  editCode: "ROOT-JOIN",
};
